### ISSUE TITLE
ТРЕБУЮ!!!

### ISSUE THREAD

**Issue by ameyuuno** [Nepomnyaschy/Spacybird#1]
Запили под iOS. Буду рубиться.

**Comment by Nepomnyaschy** [comment]
Уважаемый @yuukos.  Прямо сейчас у нас идет открытый конкурсный отбор корейцев на должность главного айоэс быдло кодера. Можете оставить свои контакты мы Вам обязательно перезвоним.
С любовью и наилучшими пожеланиями.

**Comment by ameyuuno** [comment]
Уважаемый @Nepomnyaschy. Можете обратиться к человеку, который спит на соседней кровати. Думаю его устроит. 
И пошёл ты со своей любовью. Хватит бить меня.
